on: [pull_request]
name: Static analysis
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:php7.3-alpine
        with:
          args: php-cs-fixer fix --dry-run --diff-format udiff -vvv

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://jakzal/phpqa:php7.3-alpine
        with:
          args: phpstan analyze --no-progress
